### ISSUE TITLE
404 on css files 

### ISSUE THREAD

**Issue by since1976** [north/generator-style-prototype#9] opened 2013-08-14 22:11 UTC
Hi there. 
Just trying to set this up and everything seems fine except that once I start the server and the style prototype launches in the browser all .css stylesheets appear to be 404ing. The web inspector says it can't find them at this location http://localhost:9000/styles/app.css 

I've checked the server directory and it seems like they are not being generated by compass. Do I have to manually watch the _sever folder or should that be happening automatically?

Regards
Dan

**Comment by Snugug** [comment] 2013-08-15 11:41
From what you've described, you're using the old Serve version of Style Prototypes, not this version using Grunt. Can you confirm this?

**Comment by since1976** [comment] 2013-08-21 02:11
Hey Sam sorry for the late reply.
Could be that I am using that version. How would one tell?

**Comment by since1976** [comment] 2013-08-21 02:40
Okay I uninstalled everything and started from scratch. think I have it all installed properly now except when I try and run `yo style-prototype --init` I get the following error message:

```
TypeError: Cannot redefine property: underline
    at Function.defineProperty (native)
    at addProperty (/usr/local/lib/node_modules/generator-style-prototype/node_modules/yeoman-generator/node_modules/prompt/node_modules/winston/node_modules/colors/colors.js:53:12)
    at /usr/local/lib/node_modules/generator-style-prototype/node_modules/yeoman-generator/node_modules/prompt/node_modules/winston/node_modules/colors/colors.js:189:3
    at Array.forEach (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-style-prototype/node_modules/yeoman-generator/node_modules/prompt/node_modules/winston/node_modules/colors/colors.js:184:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Any idea on how to solve this one?

**Comment by Snugug** [comment] 2013-08-28 15:11
What version of Style Prototypes are you using? Following your steps I'm unable to reproduce this error

**Comment by Snugug** [comment] 2013-10-09 14:09
Please update this issue with a response to my previous comment or I will close it.

**Closed as completed** 2014-08-12 20:31 UTC
Labels: question, 1.x, pending deletion with no action, need more info
