### ISSUE TITLE
Error on running grunt server

### ISSUE THREAD

**Issue by thiagodemellobueno** [north/generator-style-prototype#39] opened 2013-11-23 01:25 UTC
Freshly installing yo, grunt and bower.

Running yo style-prototype
answering the Qs going into the new directory and typing:

$ grunt server

Leads to the following error 

Loading "Gruntfile.js" tasks...ERROR

> > TypeError: Cannot call method 'forEach' of undefined
> > Warning: Task "server" not found. Use --force to continue.

Aborted due to warnings.

The only 'strange' thing about my setup maybe that I'm using OS X Mavericks.

**Comment by thiagodemellobueno** [comment] 2014-02-25 22:53
a819be3 does indeed seem to fix the issue.

**Comment by Snugug** [comment] 2014-08-12 20:24
Duplicate of #56

**Closed as completed by Snugug** 2014-08-12 20:24 UTC
Labels: 1.x
